### ISSUE TITLE
Metrics on KITTI Depth Completion different from paper

### ISSUE THREAD

**Issue by sabruck** [SJTU-ViSYS/SDG-Depth#1]
Thanks for sharing the code and models to your work!

Unfortunately the numbers I got from evaluating the provided model differ from the ones reported in the paper. Can you provide instructions how you obtained the metrics exactly? 
Running eval.sh I get:
mae:257.586, rmse: 685.15, imae: 0.9162, irmse:1.6021

Thank you!

**Comment by LiAngLA66** [comment]
@sabruck I'm glad you're interested in our work. I retested the code and got the expected results. You can pull the latest code and run eval.sh with reference to README. It's worth noting that our model takes the original images as inputs, not the normalized images.

**Comment by sabruck** [comment]
After reviewing it again I found indeed an error in the dataloader I caused when adjusting it to work with the KITTI dataset the way it was structured on my end and the groundtruth depth was given as model input instead of the single-scan velodyne. @LiAngLA66 Thank you so much for your reply and please excuse the extra effort I may have caused on your side.
