### ISSUE TITLE
datasets is not found

### ISSUE THREAD

**Issue by super-fsy** [SJTU-ViSYS/SDG-Depth#2]
<img width="729" alt="image" src="https://github.com/user-attachments/assets/e4ff52aa-112a-4fa9-a8e2-af60f5615d6a">
 I am having trouble downloading the dataset and am unable to complete the download. Could you please assist me with this issue? Thank you very much! @SJTU-ViSYS，@LiAngLA66

**Comment by LiAngLA66** [comment]
Hi, you can obtain the complete data from the official website (https://europe.naverlabs.com/research/computer-vision/proxy-virtual-worlds-vkitti-1/).
